#!/usr/bin/sh

DIR="`pwd`"
cd `dirname $0`

if [[ $1 == 'static' ]]; then
    RUSTFLAGS='-C target-feature=+crt-static' cargo build --release || exit 1
    shift
else
    cargo build --release || exit 1
fi
cp ./target/release/swl ./swlc

cd "$DIR"
if [ $# -ge 1 ]; then
    cargo run --release $*
else
    cargo build --release
fi
