[package]
name = "lang"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

[[bin]]
name = "lang"
path = "src/main.rs"

[target.x86_64-pc-linux-gcc]
rustflags = ["-C", "target-feature=+crt-static"]
